modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="qikas_tconlib"
version="0.1.0"
displayName="Qika's Tinkering Lib"
displayURL="https://github.com/QikaHome/Tconlib"
credits="none"
authors="Qikahome"

[[dependencies.qikas_tconlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.qikas_tconlib]]
    modId="tconstruct"
    mandatory=true
    versionRange="any"
    ordering="AFTER"
    side="BOTH"
